/*Interfaces for the FFProbeData object returned by the ffprobe command.*/

interface Stream {
  index: number;
  codec_name: string;
  codec_long_name: string;
  profile: string;
  codec_type: string;
  codec_tag_string: string;
  codec_tag: string;
  width: number;
  height: number;
  coded_width: number;
  coded_height: number;
  closed_captions: number;
  film_grain: number;
  has_b_frames: number;
  sample_aspect_ratio: string;
  display_aspect_ratio: string;
  pix_fmt: string;
  level: number;
  color_range: string;
  color_space: string;
  color_transfer: string;
  color_primaries: string;
  chroma_location: string;
  field_order: string;
  refs: number;
  is_avc: string;
  nal_length_size: number;
  id: string;
  r_frame_rate: string;
  avg_frame_rate: string;
  time_base: string;
  start_pts: number;
  start_time: number;
  duration_ts: number;
  duration: 'string';
  bit_rate: number;
  max_bit_rate: string;
  bits_per_raw_sample: number;
  nb_frames: number;
  nb_read_frames: string;
  nb_read_packets: string;
  extradata_size: number;
  tags: object;
  disposition: object;
}

interface Format {
  filename: string;
  nb_streams: number;
  nb_programs: number;
  format_name: string;
  format_long_name: string;
  start_time: number;
  duration: number;
  size: number;
  bit_rate: number;
  probe_score: number;
  tags: {
    major_brand: string;
    minor_version: string;
    compatible_brands: string;
    creation_time: string;
  };
}

export interface FFProbeData {
  streams: Stream[];
  format: Format;
}

// Interfaces for the metadata object returned by the video-metadata IPC handler.

export interface Metadata {
  streams: {
    width: number;
    height: number;
    r_frame_rate: string;
    duration: string;
    codec_type: string;
    rotation?: number;
  }[];
  format: {
    tags: {
      creation_time?: string;
    };
  };
}

export interface FirstFrameArgs {
  start_frame: number;
  end_frame: number;
  step: number;
  factor: number;
}

export interface ProjectConfig {
  // Path to the main directory where all the projects will be stored.
  mainDirectory: string;

  // Path to the root directory of the project where all the project files and folders will be stored.
  projectDirectory: string;

  // Type of the project: "uav", "oblique" or "ipcam".
  type: string;

  // Path to the video file selected by the user for the project.
  videoPath: string;

  // Path to the transformation matrix file .json generated by the user and used in all the project.
  matrixPath: string;

  // Path to the settings file .json where all the project settings are stored.
  settingsPath: string;

  // Path to the folder where all the extracted frames from the video will be stored.
  framesPath: string;

  // Path to the cross-section files .json. This file contains all the information about the sections defined by the user.
  xsectionsPath: string;

  // Path to the bounding box file .json defining the area of interest for the analysis.
  bboxPath: string;

  // Path to the mask file .png defined by the user to exclude areas from the analysis.
  maskPath: string;

  // Path to the results file where all the processing results will be stored.
  // It is a json file.
  resultsPath: string;

  // Path to the log file where application logs will be stored.
  // All the success and error messages will be logged here.
  logsPath: string;

  // Path to the first frame image extracted from the video.
  firstFrame: string;

  // Path to use as default when opening file dialogs.
  defaultFilesPath: string;

  // Prefix to add to the name of the files generated by the application. Is used in development mode.
  filePrefix: string;
}

interface Point {
  x: number;
  y: number;
}

export interface pixelSizeHandleArgs {
  dirPoints: Point[];
  rwPoints: Point[];
  pixelSize: number;
  rwLength: number;
}
